name: publish
on: [push]
jobs:
publish-hello-docker-image:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: swhite2016
username: ${{ secrets.DOCKER_USERNAME }}
password: ${{ secrets.DOCKER_PASSWORD }}
- name: Build the docker jmx image
run: |
       docker build . --tag swhite2016/jmx:latest
       docker run swhite2016/jmx:latest
       docker swhite2016/jmx:latest
