name: publish
on: [push]
  workflow_call:
    secrets:
      REPO_TOKEN:
        required: true
jobs:
publish-hello-docker-image:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: swhite2016
username: ${{ github.actor }}
password: ${{ github.token }}
- name: Build the docker-imqbrokerd Docker image
run: |
       docker build . --tag swhite2016/docker-imqbrokerd:latest
       docker run swhite2016/docker-imqbrokerd:latest
       docker swhite2016/docker-imqbrokerd:latest
