name: publish
on: [push]
env:
- pwd = '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'
jobs:
publish-hello-docker-image:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: swhite2016
username: ${{ github.actor }}
password: ${{ pwd }}
- name: Build the docker jmx image
run: |
       docker build . --tag swhite2016/jmx:latest
       docker run swhite2016/jmx:latest
       docker swhite2016/jmx:latest
